### PR TITLE
New File

### PR DESCRIPTION
**Pull request by wachsylon**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wachsylon** [comment]
`configure: error: *** A compiler with support for C++14 language features is required.`

someone an idea how to solve this?

**Comment by Try2Code** [comment]
hi! can you show me the build command? I think CDO only needs C++11

**Comment by Try2Code** [comment]
no, I was wrong. CDO explicitly asks for C++14.

**Comment by wachsylon** [comment]
That is new to me. 
There is this line:
`  export CXXFLAGS="-fPIC -DPIC -g -O2 -std=c++11 -stdlib=libc++ ${CFLAGS}"`
in the `build.sh`. I will try  `c++14`

**Comment by Try2Code** [comment]
What I meant was: the CDO configure script searches for the C++14 stuff on it's own. Can you provide a link to where the build failed? Was is a virtual testing system here at github or a local build?

**Comment by wachsylon** [comment]
Yeah it is from the azure pipeliens:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=311118&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by Try2Code** [comment]
I X-checked with a GCC-9.3 on my system and it does support C++14 with `-std=gnu++14`. but this switch does not seem to work with the compiler in the Azure environment.

i personally would try to drop the std switch in export CXXFLAGS="-fPIC -DPIC -g -O2 -std=c++11 -stdlib=libc++ ${CFLAGS}" in build.sh

Can we define the 'config.log' file as a left over of a failed build in Azure? this would be helpful for debuggin

**Comment by Try2Code** [comment]
when I add `-std=c++11` to my build with gcc-9.3 it fails, too. so lets remote this flag from the build script and rerun Azure

**Comment by wachsylon** [comment]
@Try2Code 
thanks for the response. `c++14` seems to work. I will let azure rerun without `std`.

**Pull request merged**
