### PR TITLE
check 2.0.6 - again

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Try2Code** [comment]
@conda-forge-admin, please rerender

**Comment by Try2Code** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564428&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

hi guys! @ocefpaf @akrherz 

can anyone tell me, whats going on? i just see the 'exit 1' but no further info on what failed

**Comment by akrherz** [comment]
Hi @Try2Code , sorry, I am unsure what is happening here :(

**Comment by Try2Code** [comment]
the osx error is legit - users already reported this elsewhere.

I think got the linux thing: `cdo -h` indeed returns exit code -1

sry, didn't expect this to happen at all :shrug:

**Comment by Try2Code** [comment]
@ocefpaf @akrherz - I wait for a bugfix release and keep this ticket open

**Comment by Try2Code** [comment]
hi guys! I will close this one because cdo-2.1.0 was just released

**Pull request closed without merging**
