### PR TITLE
Update to recent version

### PR DESCRIPTION
**Pull request by wachsylon**

### CODE REVIEW

**Comment by Try2Code** [comment]
@ocefpaf @wachsylon 

i checked the build with installing

```
conda install conda-forge/label/dev::cdo
```

the binary works fine - I hope I did nothing wrong with the merge ;-)

As you both have discussed in #38 the 'dev' branch was the correct target. Should it stay that way? Or is this just a temporary thing?

cheers

**Comment by ocefpaf** [comment]
> Should it stay that way? Or is this just a temporary thing?

This is the stable release, right? So we can target the `master` branch and get this publish in the `main` channel. No need for dev here.

**Comment by Try2Code** [comment]
So let's keep it the way it is and you @wachsylon take action, if you want it to be in the ```master```, ok?

**Comment by ocefpaf** [comment]
> I would like to keep the dev branch for a while so that I can evaluate how many users are particularly interested in CDOs with CMOR support.

Keeping the dev branch is fine. Feel free to keep updating it with dev releases.

**Pull request merged**
