### PR TITLE
Re render

### PR DESCRIPTION
**Pull request by ocefpaf**
For some reason the re-rendering did not happen in #50

### CODE REVIEW

**Comment by Try2Code** [comment]
hi @ocefpaf !

How Can I trigger the re-render of the build? I use cdo during some of my automated tests and they fail currently due to missing shared objects: https://travis-ci.org/Try2Code/cdo-bindings/jobs/451749151

Could a re-render help here?

**Comment by ocefpaf** [comment]
> How Can I trigger the re-render of the build?

You can do that with the webservices:

https://conda-forge.org/docs/webservice.html

> I use cdo during some of my automated tests and they fail currently due to missing shared objects: [travis-ci.org/Try2Code/cdo-bindings/jobs/451749151](https://travis-ci.org/Try2Code/cdo-bindings/jobs/451749151)
> 
> Could a re-render help here?

Not sure. That errors seems like something else. The Re-render will only update the feedstock boilerplate for the build.

**Comment by ocefpaf** [comment]
> at least a first test worked now in TravisCI ...

Glad it is fixed :smile:

**Comment by Try2Code** [comment]
yeah, all other test run now, too. Cool thing :hand:

**Pull request merged**
