### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by wachsylon**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
You'll probably need to rebuild `cmor` first.

**Comment by Try2Code** [comment]
hi @wachsylon!

I built the package from your 'dev' branch and installed it with `conda install --offline`. but then I got 2 missing shared object in the evironment: `libproj.so.19` and `libjson-c.so.4`
but that might be expectable since I build from source

**Comment by wachsylon** [comment]
> You'll probably need to rebuild cmor first.

With the cmor-feedstock for conda-forge or a new version from home repo?

**Comment by ocefpaf** [comment]
> With the cmor-feedstock for conda-forge or a new version from home repo?

Just a new re-rendered version would do but you can update it the latest version upsream too if you want.

**Comment by wachsylon** [comment]
@ocefpaf 
For the new CMOR version and the new CDO file, it finally seems to work :)

**Comment by ocefpaf** [comment]
LGTM! Merge away!

**Comment by wachsylon** [comment]
Great.

> LGTM! Merge away!

How?

**Comment by ocefpaf** [comment]
I though you had commit rights here. Sorry.

**Pull request merged**
