### PR TITLE
update to cdo-1.9.8

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Try2Code** [comment]
@ocefpaf  how can I initiate re-rendering of the downloadable binaries?

**Comment by ocefpaf** [comment]
> @ocefpaf how can I initiate re-rendering of the downloadable binaries?

Not sure I follow. Do you want to restart the build or re-render the recipe?

**Comment by Try2Code** [comment]
I updated the recipe and now I thought there need to be a step for generating the binary, that are installed by ```conda install cdo```

not sure if _re-render the recipe_ is the term for this...

**Comment by ocefpaf** [comment]
> I updated the recipe and now I thought there need to be a step for generating the binary, that are installed by `conda install cdo`
> 
> not sure if _re-render the recipe_ is the term for this...

Ah. Got it. The recipe builds the binary and will be updated as soon as we merge this.

Re-rendering "updates" te boilerplate stuff for conda-forge. Like, right now, due to an update on the proj library, re-rendering will use proj 6.1.2. Let me do that here and we can merge this one.

**Pull request merged**
