### PR TITLE
Rc

### PR DESCRIPTION
**Pull request by ocefpaf**
Same as #38 but pointing to the `dev` channel.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@wachsylon I'm getting a 404 for the source:

```
Error: HTTP 404 NOT FOUND for url <https://code.zmaw.de/attachments/download/18082/cdo-1.9.5rc2.tar.gz>
```

**Comment by wachsylon** [comment]
I am sorry, there is a new CDO version.
Could you merge this? 858b0a6e793fe3d89d94228bfcd6acc6f7c2b24e
As soon as 1.9.5 is available, I will change the corresponding download attributes.

**Comment by ocefpaf** [comment]
Awesome! Now Travis-CI is failing again:

```
Missing CONDA_BUILD_SYSROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
/Users/travis/miniconda3/bin/run_conda_forge_build_setup: line 78: shell_session_update: command not found
```

**Comment by ocefpaf** [comment]
:tada:

**Comment by wachsylon** [comment]
YEAH! This worked:
`./conda install cdo -n cdocmor -c conda-forge/label/dev -c conda-forge`
There is a priority in the order of channel specification, right? This installed `cdo` from the `dev` channel and all other packages from normal conda-forge channel. If I write instead:
`./conda install cdo -n cdocmor -c conda-forge/label/dev`
I receive:
```
PackageNotFoundError: Packages missing in current channels:
            
  - cdo -> cmor
  - cdo -> eccodes
  - cdo -> ossuuid 1.6.2 0
```
Thank you very very much, @ocefpaf !

**Comment by ocefpaf** [comment]
@wachsylon the safest way to install it is with:

```
conda create --name CDO conda-forge/label/dev::cdo
```

Conda is not very smart when using channel/labels so we must use the `::` syntax to get only `cdo` from `dev` and nothing else. Also, using envs is always recommended.

**Comment by wachsylon** [comment]
When I do so, I get
```
PackageNotFoundError: Packages missing in current channels:
            
  - conda-forge/label/dev::cdo
```

**Comment by ocefpaf** [comment]
Try updating your `conda`. The command above uses some new features that you may be missing there.

**Comment by wachsylon** [comment]
Yes. Now it works.

**Comment by ocefpaf** [comment]
Glad it is working! The `::` syntax is a must these days, it will save you from creating broken envs when you only want a single package from another channel.
(It is the closest we have from the `pip --pre` command.)

**Comment by wachsylon** [comment]
Good to know. But the standard conda-forge channel is still needed. Without it, I get:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/label/dev::cdo
  - cmor
  - conda-forge/label/dev::cdo
  - eccodes
  - conda-forge/label/dev::cdo
  - ossuuid==1.6.2=0
```

**Comment by wachsylon** [comment]
Which is pretty obvious of course - however I need it for the instructions :)

**Comment by ocefpaf** [comment]
Yes, sorry. I have `conda-forge` on my `.condarc` so I forgot about that. BTW, here is my `.condarc` just in case:

```
> cat ~/.condarc 
show_channel_urls: true
add_pip_as_python_dependency: true
channels:
  - conda-forge
  - defaults
create_default_packages:
  - pip
  - ipykernel
  - jupyter
```

**Pull request merged**
