### PR TITLE
Newdev

### PR DESCRIPTION
**Pull request by wachsylon**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wachsylon** [comment]
@conda-forge-admin, please rerender

**Comment by Try2Code** [comment]
> @ocefpaf @Try2Code hi, since the last update is long ago, I thought it would be a good idea to branch from the recent `main`, update
> 
> ```
> recipe/build.sh
> recipe/meta.yaml
> ```
> 
> and then merge back to `dev`. unfortunately, the mr now looks way more complicated. If you have another idea how to publish a new `dev` branch which includes cmor, I would highly appreciate it. I urgently need the recent version of cdo to be installable with cmor.
> 
> So thank you very much for any hints! Best, Fabi



> @ocefpaf @Try2Code hi, since the last update is long ago, I thought it would be a good idea to branch from the recent `main`, update
> 
> ```
> recipe/build.sh
> recipe/meta.yaml
> ```
> 
> and then merge back to `dev`. unfortunately, the mr now looks way more complicated. If you have another idea how to publish a new `dev` branch which includes cmor, I would highly appreciate it. I urgently need the recent version of cdo to be installable with cmor.
> 
> So thank you very much for any hints! Best, Fabi

hi!

branching off of `main` is a very good idea, but then merge this with `dev` will cause problems. My recommendation is more like: take `main` and add as little as u need manually from dev to make it work (json/cmor and so on). But no further additions from an out-dated dev version. This is exactly what u want to avoid.

I think the osx-arm testing is broken at the moment, sry

**Comment by wachsylon** [comment]
@Try2Code 

In order to show the only slight deviation from main, I created a second [MR](https://github.com/conda-forge/cdo-feedstock/pull/156), and, surprisingly, the osx-arm test succeeded. Probably time heels all wounds?

> but then merge this with dev will cause problems

Yeah, I know. I rather want to *replace* the existing dev with this new dev. I think this is the same procedure as @akrherz  did [last time](https://github.com/conda-forge/cdo-feedstock/pull/142). I also think this is not possible for me to do as I can only do MRs in existing branches. Or is there a way?

As the tests in the other MR did pass, can we just use my `newdev` as `conda-forge:dev`?

Thanks and best.

**Comment by wachsylon** [comment]
@akrherz 

Sorry for bothering. What do you think?
Can you give me some advice?

**Comment by akrherz** [comment]
No worries about bothering me, I am helper of this repo :)  Do you want the dev branch to be force pushed updated to current main branch  and then can resubmit a new PR?

**Comment by wachsylon** [comment]
@arkherz sounds good

**Comment by akrherz** [comment]
whoa, I think it is done now, but am unsure what happened with this PR :/

**Pull request closed without merging**
