### PR TITLE
Rebuild with jasper 2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

Attempting to march versions forward.

### CODE REVIEW

**Comment by akrherz** [comment]
package dependency issues, unclear if we need to step `jasper 2` first or `hdf5 1.12.1`.  Gonna try jasper first

**Comment by akrherz** [comment]
@ocefpaf A Green PR for your consideration. If merged, I'll follow up with a hdf5 migration PR.

**Comment by akrherz** [comment]
impatient ping of @ocefpaf on green PR, sorry to be annoying.

**Comment by ocefpaf** [comment]
> impatient ping of @ocefpaf on green PR, sorry to be annoying.

No problem at all! Thanks for all this effort to get our stack of packages back into shape.

**Pull request merged**
