### PR TITLE
CDO version and download link

### PR DESCRIPTION
**Pull request by wachsylon**
Need a PR to update the version from time to time.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@wachsylon I see many old commit in there, maybe you need to update your fork?

**Comment by wachsylon** [comment]
I probably should have started with https://github.com/conda-forge/cdo-feedstock/pull/44/commits/1ca7bd219e715abbc6174de6645bc1f9e3b4a99f before the PR, right? Sorry. Should I repeat the PR?

**Comment by wachsylon** [comment]
As you can see in https://github.com/conda-forge/cdo-feedstock/pull/44/files it is only the download link which should be modified.

**Comment by ocefpaf** [comment]
> I probably should have started with 1ca7bd2 before the PR, right? Sorry. Should I repeat the PR?

No need. WE can squash and merge.

**Pull request merged**
