### PR TITLE
update to cdo-1.9.4

### PR DESCRIPTION
**Pull request by Try2Code**
hi!
cdo-1.9.4 was release - so here is the changeset for the conda-forge pkg

### CODE REVIEW

**Comment by Try2Code** [comment]
hi brian!
i checked the logs, too. will check the build process in detail using the condaforge docker image. we test cdo on many linux systems incl.  32bit and cygwin. afaik the gcc used for building is 4.8.x, could be its too old for C++11.  or maybe its just a missing <cstring>

cheers
ralf

⁣Gesendet mit BlueMail ​

**Comment by Try2Code** [comment]
I have trouble using the linux-anvil image for debugging, could start or build it and finally created a ticked: https://github.com/conda-forge/docker-images/issues/66

**Comment by Try2Code** [comment]
I used an ubuntu:14.04 image instead. got source code fixed and will add this to the main CDO repo.

**Comment by ocefpaf** [comment]
Sorry to hear you had trouble with our docker image. I was unable to reproduce that error :-/

**Comment by Try2Code** [comment]
aaaand sry for the dirty commit - should have cleaned that version number thing up myself

**Comment by Try2Code** [comment]
this seems to cause for fun than I initially thought - will have a closer look into it next week

**Comment by Try2Code** [comment]
on the ubuntu-14.04 image i cannot reproduce the errors  - all checks run fine. 

i will try centos:7

**Comment by Try2Code** [comment]
no failing checks under centos:7

**Comment by Try2Code** [comment]
any idea on how we can proceed?

**Comment by ocefpaf** [comment]
> any idea on how we can proceed?

I'm at PyCon at the moment. I'm heading back home today and I'll take a look at this ASAP. However, b/c linux is passing, I'm OK if you merge this to cash that in and we can open an issue to solve OS X later.

**Comment by Try2Code** [comment]
no hurry - I finally found a machine to hopefully run the condaforge/linux-anvil image. Will take some days to get access and test it. since cdo-1.9.4 si just release, IMO we are not in a big hurry to make it available via conda. 

Just to make that clear for me:  the failing test happened on linux-anvil - not on the MacOS image, right?

**Comment by Try2Code** [comment]
aaah, no, I misread the log at https://travis-ci.org/conda-forge/cdo-feedstock/builds/377767851?utm_source=github_status&utm_medium=notification

it is a macOS-error. I will check this on a local Mac here at work. maybe its easier than I thought in the first place ...

**Comment by Try2Code** [comment]
fnally I can reproduce the error on the mac I have access to. With normal manual build, everything works. but the conda build has the error.

**Comment by Try2Code** [comment]
any reason why openmp is disable on macos?

**Comment by Try2Code** [comment]
damn - it still has this issue although it was successful on my system :-\

will try something different ...

**Comment by Try2Code** [comment]
got it!!!

**Comment by Try2Code** [comment]
both changes are already part of the dev version and will make it into next release

**Comment by ocefpaf** [comment]
> any reason why openmp is disabled on macos? 

I'm not sure what is the status of `openmp` with `clang`. We don't use `gcc` on  OS X :unamused: 

This LGTM, should we merge?

**Comment by Try2Code** [comment]
```With the release of Clang 3.8.0, OpenMP 3.1 support is enabled in Clang by default, ... ``` (https://openmp.llvm.org)

CDO building just checks if it can find a useful openmp compile flag. If not, it  just steps on without it. I dont see a real issue. you can check the log: https://travis-ci.org/conda-forge/cdo-feedstock/jobs/380162801#L464

tbh I dont understand the philosophy of MacOS wrt compilers. I mean, there is a binary named ```gcc``` in /usr/bin but it is a clang compiler, REAL gcc can be installed with macports somewhere else but with the same name ...

god, does anyone wants to use THAT system for programming on system level?

**Comment by Try2Code** [comment]
@ocefpaf yes - there is no new release, yet ;-)

**Comment by ocefpaf** [comment]
OK. Merging. BTW, self-merges are fair game when updating versions, no need to wait for a review.

**Comment by Try2Code** [comment]
self-merges? so I am allowed to merging stuff into cdo-feedstock?

**Comment by ocefpaf** [comment]
I thought we added you as a maintainer but I just notice we did not! If you want I can send a PR doing that right now, it will grant you commit rights here.

**Comment by Try2Code** [comment]
yeah, ok

**Pull request merged**
