### PR TITLE
rebuild libnetcdf=4.9.2 + libxml2 2.11

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
OK, will try this again in an hour or two or see if the bot shows up before then...

**Comment by akrherz** [comment]
@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
Perhaps another instance with libxml2 + libnetcdf 4.9.2 needing to migrate together.

**Comment by akrherz** [comment]
waiting on new magics build for osx_64

**Comment by akrherz** [comment]
transient build failure, serenity now!  conda-forge/magics-feedstock#127

**Comment by akrherz** [comment]
@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
Grrr, we still need some help getting that magics failed job restarted.  Otherwise, will need to migrate proj as well here.  Will wait another day.

**Comment by zklaus** [comment]
@akrherz, thanks for pushing forward with this. I am also mostly interested in getting cdo up to speed; seems we are quite aligned :wink:.

Anyways, do you know the graph view on the conda-forge status? Since you mentioned something being in `AWAITING-PARENTS`, I know you have been at https://conda-forge.org/status/#libnetcdf492. If you then click on "GRAPH", you can see the whole dependency graph of outstanding migrations and if you open just the graph in a new tab (via right-click, "open image in new tab"), you can use text search to find the package you are interested in and use direct links from the graph nodes to the corresponding PRs.

**Comment by Try2Code** [comment]
> @akrherz, thanks for pushing forward with this. I am also mostly interested in getting cdo up to speed; seems we are quite aligned wink.
> 

hi @zklaus !
What kind of speed are u talking about?

**Comment by akrherz** [comment]
> Anyways, do you know the graph view on the conda-forge status?

Thanks, I did know about that, but did not know about the additional functionality that happens when opening that image in a new tab! 

> What kind of speed are u talking about?

@Try2Code , it is just a saying meaning to bring the package up to all current conda-forge current/newest builds.

**Comment by Try2Code** [comment]
thx for clarification @akrherz 
Being a part-time CDO developer the terms 'cdo' and 'speed' in the same sentence always gets me triggered :man_shrugging:

**Comment by akrherz** [comment]
OK, magics-feedstock run was redone successfully, will try this PR shortly again.

**Pull request closed without merging**
