### PR TITLE
Update to new file

### PR DESCRIPTION
**Pull request by wachsylon**
<code>@<space/>conda-forge-admin, please rerender</code>

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

New file.

### CODE REVIEW

**Comment by wachsylon** [comment]
Is everything O.K.?

**Comment by Try2Code** [comment]
sieht doch alles gut aus ;-)

For a X-check I need to checkout your fork, change to branch ```dev``` and call ```conda-build ./recipe ``` right?

**Comment by Try2Code** [comment]
got this error

```

Resource usage statistics from building cdo:
   Process count: 16
   CPU time: Sys=0:00:09.0, User=0:03:05.0
   Memory: 869.9M
   Disk usage: 364.1M
   Time elapsed: 0:10:08.2

Packaging cdo
INFO:conda_build.build:Packaging cdo
INFO conda_build.build:build(1540): Packaging cdo
/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/environ.py:418: UserWarning: The environment variable 'LIBS' is undefined.
  UserWarning
Packaging cdo-1.9.8rc2-h1c2f66e_0
INFO:conda_build.build:Packaging cdo-1.9.8rc2-h1c2f66e_0
INFO conda_build.build:bundle_conda(879): Packaging cdo-1.9.8rc2-h1c2f66e_0
number of files: 1
ERROR :: get_rpaths_raw()=['/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/lib:/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib'] and patchelf=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/lib:/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib disagree for /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/cdo :: 
Warning: rpath /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/lib is outside prefix /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol (removing it)
Traceback (most recent call last):
  File "/home/ram/.miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2313, in build_tree
    notest=notest,
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1612, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 990, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 855, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 1083, in post_build
    post_process_shared_lib(m, f, prefix_files)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 1032, in post_process_shared_lib
    mk_relative_linux(f, m.config.host_prefix, rpaths=rpaths)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 468, in mk_relative_linux
    set_rpath(old_matching='*', new_rpath=rpath, file=elf)
  File "/home/ram/.miniconda3/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 198, in set_rpath
    binary.write(file)
MemoryError: std::bad_alloc
```

but the binary seems to work
```
1]  (git)-[dev]-% /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/cdo -V        [Tue 2019-10-08|14:59:48]
Climate Data Operators version 1.9.8rc2 (https://mpimet.mpg.de/cdo)
System: x86_64-conda_cos6-linux-gnu
CXX Compiler: /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -fPIC -DPIC -g -O2 -std=c++11 -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/work=/usr/local/src/conda/cdo-1.9.8rc2 -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix -fopenmp 
CXX version : unknown
C Compiler: /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/work=/usr/local/src/conda/cdo-1.9.8rc2 -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix -fopenmp  
C version : unknown
F77 Compiler: /home/ram/.miniconda3/conda-bld/cdo_1570538639499/_build_env/bin/x86_64-conda_cos6-linux-gnu-gfortran -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/work=/usr/local/src/conda/cdo-1.9.8rc2 -fdebug-prefix-map=/home/ram/.miniconda3/conda-bld/cdo_1570538639499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix
F77 version : unknown
Features: 15GB 8threads C++11 Fortran DATA PTHREADS OpenMP HDF5 NC4/HDF5/threadsafe OPeNDAP UDUNITS2 PROJ XML2 CURL FFTW3 CMOR SSE3
Libraries: HDF5/1.10.5 proj/6.1.1 CMOR/3.5.0 xml2/2.9.9 curl/7.65.3
Filetypes: srv ext ieg grb1 grb2 nc1 nc2 nc4 nc4c nc5 
     CDI library version : 1.9.8rc2
 cgribex library version : 1.9.4
 ecCodes library version : 2.13.1
  NetCDF library version : 4.6.2 of Aug 31 2019 03:28:55 $
    hdf5 library version : 1.10.5 threadsafe
    exse library version : 1.4.1
    FILE library version : 1.8.3

```

**Comment by Try2Code** [comment]
I do a re-check with a brand-new conda (miniconda3) ...

**Comment by Try2Code** [comment]
with a recent miniconda3 it works fine

**Comment by wachsylon** [comment]
Great, thanks.

**Pull request merged**
