### PR TITLE
Update to cdo-2.0.4

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks.  Is there a reason why you did not `rerender` this?

**Comment by akrherz** [comment]
> Am I wrong about this?

Yes, you either have to do it manually from the command line locally or specify it here and now I see you just merged this PR.  Please don't do that.

**Comment by Try2Code** [comment]
@conda-forge-admin, please rerender

**Comment by Try2Code** [comment]
> > Am I wrong about this?
> 
> Yes, you either have to do it manually from the command line locally or specify it here and now I see you just merged this PR. Please don't do that.

Should you merge this request?

**Comment by akrherz** [comment]
> Should you merge this request?

You already did!

**Comment by Try2Code** [comment]
> > Should you merge this request?
> 
> You already did!

I know :rofl: - I meant in the future

**Comment by akrherz** [comment]
> I know  - I meant in the future

In general, it is nice to have somebody else sign off on the PR before merging, but there's not many folks working on this repo.  It is a best practice though to always rerender to give confidence that the build is happening with the latest/greatest conda-forge CI scripts / pinning...

**Comment by Try2Code** [comment]
alright - I just want to improve how I work with this. I also like the idea of other ppl having a look into MRs before merging. So let's stick to this. Will wait for ether u or oce to get a review. After that it does not matter, who does the merge I think

**Pull request merged**
