### PR TITLE
Updated to recent version

### PR DESCRIPTION
**Pull request by wachsylon**
@conda-forge-admin, please rerender

Update to recent version which is used for MPI-ESM1-2 for CMIP6 DECK experiments

### CODE REVIEW

**Comment by wachsylon** [comment]
Ok how can I get access to the config logs of the failed tests? Does anyone have an idea what is going wrong?

**Comment by Try2Code** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=70628

**Comment by Try2Code** [comment]
https://github.com/conda-forge/cdo-feedstock/pull/67/checks

from there u can select the builds and than u click on "errors/warning" link

**Comment by ocefpaf** [comment]
LGTM!

**Comment by ocefpaf** [comment]
Just moved them to the `dev` label manually now. I need to fix the channel upload here. PR in a moment.

**Pull request merged**
