### PR TITLE
update to cdo-1.9.2; replace grib_api with eccodes

### PR DESCRIPTION
**Pull request by Try2Code**
Hi!
I updated the conda-forge package for cdo with a jump from 1.9.0 to 1.9.2. In addition I replaced the outdated grib_api library with its follower eccodes. 

hth
ralf

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @Try2Code!

**Comment by Try2Code** [comment]
I wanted to use conda to check by cdo-bindings with different cdo binaries. But I noticed, that all binaries older than 1.9.0 did not work, because an older libnetcdf.so files was missing. 
Could this be fixed by setting an explicit version for the netcdf dependency rather than '4.4.*'?

**Comment by ocefpaf** [comment]
> Could this be fixed by setting an explicit version for the netcdf dependency rather than '4.4.*'?

Ideally we should create LTS branches and update the pinning on those. Do you want to do that? If so I can create the branches for you.

**Comment by Try2Code** [comment]
I didnt want to introduce new branches or any new stuff,which would mean more work for you. I just thought that older versions of packages are supposed to work. If that's not the case, I will try to find  another solution - no big deal.

**Comment by ocefpaf** [comment]
It is up to you. Creating the LTS branches is easy. Sending PRs to re-build them that takes a little more effort, but not that much. If you want to do it you can create PRs for the old version targeting `master` and I'll create the branches later so you can point them there.

**Pull request merged**
