### PR TITLE
Update to release 2.0.0

### PR DESCRIPTION
**Pull request by jomey**
Updates version number, SHA, and resetting the build number

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by jomey** [comment]
@conda-forge-admin, please rerender

**Comment by jomey** [comment]
Not sure what the preferred way is to ensure a C++14 compatible compiler for the builds.
Any help appreciated and I will update the PR

**Comment by akrherz** [comment]
Is the issue what is happening with the `CXXFLAGS` in `recipe/build.sh` ?

**Comment by jomey** [comment]
> Is the issue what is happening with the `CXXFLAGS` in `recipe/build.sh` ?

I am thinking of bumping the flag for `std`, here:
https://github.com/conda-forge/cdo-feedstock/blob/660f7968a14f50af516f25d3b215b6a91ff2f88b/recipe/build.sh#L4

**Comment by akrherz** [comment]
The conflicting `-g -O2` is odd, but not germane to this PR and dates back many years.  It appears like it will go green, thanks!

**Review by akrherz — APPROVED** [review]

**Comment by jomey** [comment]
> The conflicting `-g -O2` is odd, but not germane to this PR and dates back many years. It appears like it will go green, thanks!

Happy to issue a new PR after this one.
Let me know what the preferred flag is.

**Comment by akrherz** [comment]
I assume this is the problem now on MacOS

>  checking for x86_64-apple-darwin13.4.0-cpp... no

**Comment by jomey** [comment]
> I assume this is the problem now on MacOS
> 
> > checking for x86_64-apple-darwin13.4.0-cpp... no

Add this to the `meta.yml`:
```{yml}
requirements:
  build:
    - clangxx_osx-64 # [os x]
```

**Comment by akrherz** [comment]
> Should this be added to the `meta.yml`:

Sorry, I am unsure how this is supposed to work on a Mac :(

**Comment by jomey** [comment]
Maybe @ocefpaf or @Try2Code have some experience getting the build setup for OS X and C++14 on Azure?

**Comment by Try2Code** [comment]
> Maybe @ocefpaf or @Try2Code have some experience getting the build setup for OS X and C++14 on Azure?

hi!
AFAIK the MacOS build in conda is limited wrt to CDO features. I always recommend to use the macports version. in general the necessary compile flags are set by CDO's configure script. It knows which CXX features are needed, like c++14.

**Comment by Try2Code** [comment]
has anyone tried this build locally? @jomey @akrherz 
I don't have access to a Mac, sry

**Comment by jomey** [comment]
> has anyone tried this build locally? @jomey @akrherz I don't have access to a Mac, sry

Same boat here. I am on Linux and have no access to a Mac to debug.

**Comment by jomey** [comment]
> > Maybe @ocefpaf or @Try2Code have some experience getting the build setup for OS X and C++14 on Azure?
> 
> hi! AFAIK the MacOS build in conda is limited wrt to CDO features. I always recommend to use the macports version. in general the necessary compile flags are set by CDO's configure script. It knows which CXX features are needed, like c++14.

Thanks for the insight.

Both, brew and macport, seem to be actively maintained.
How do people feel about only maintaining a Linux built with conda since three of us have no access to a Mac?

**Comment by akrherz** [comment]
> How do people feel about only maintaining a Linux built with conda since three of us have no access to a Mac?

We'd want to review what macports is using for configure options and replicate them here.  We should be able to figure this out.

**Comment by akrherz** [comment]
setting the environment variable

`CPP=clang-cpp` 

appears to work locally for me.  I am blissfully ignorant if it is the right thing to do or not :(

**Comment by akrherz** [comment]
> AFAIK the MacOS build in conda is limited wrt to CDO features.

@Try2Code , would you be willing to open additional issues here with those missing features so that we can resolve any of these functionality gaps?

**Comment by Try2Code** [comment]
found a mac, will try @akrherz

**Comment by Try2Code** [comment]
> > AFAIK the MacOS build in conda is limited wrt to CDO features.
> 
> @Try2Code , would you be willing to open additional issues here with those missing features so that we can resolve any of these functionality gaps?

let me test this thing manually a bit before I start involving more ppl

**Comment by Try2Code** [comment]
@jomey 

I could test a bit the mac and could build and test cdo locally using `conda build recipe` with this changeset
```diff
diff --git a/recipe/build.sh b/recipe/build.sh
index 8ce6506..9530b34 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 if [[ $(uname) == 'Darwin' ]]; then
-  export CXXFLAGS="-fPIC -DPIC -g -O2 -std=c++14 -stdlib=libc++ ${CFLAGS}"
+  export CXX=clang++
+  export CC=clang
+  export CXXFLAGS="-fPIC -DPIC -g -O2 ${CFLAGS}"
+  export CPP=clang-cpp
   export LDFLAGS="${LDFLAGS} -fopenmp"
   ARGS=""
 elif [[ $(uname) == Linux ]]; then
```

I cannot commit to your branch of course - would be nice to apply this  to your release-2.0.0 branch. CI will tell us the rest I think.

**Comment by Try2Code** [comment]
> > I cannot commit to your branch of course
> 
> Sure you can, you are a repo maintainer here and that works unless specifically disabled.

but it still is jomey's  repo, isnt it? So how could I have write access? are access right copied with the fork?

**Comment by akrherz** [comment]
> but it still is jomey's repo, isnt it? So how could I have write access? are access right copied with the fork?

Yes, but you get special write access to jomey's branch specified with this PR.  When you submit a PR, there is a special checkbox that is enabled by default to allow repo owners to commit to your PR branch.

**Comment by jomey** [comment]
Thank you @akrherz and @Try2Code for the guidance and help with PR.
Pipelines look promising

**Pull request merged**
