### PR TITLE
add v2.4.3

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Try2Code** [comment]
@akrherz @ocefpaf -  hi guys!

I have non-admin access to an apple M1 system and could build and check cdo. But I don't understand the CI regarding osx arm. Does any of u understand, why it fails?

thx in advance :wave:

**Comment by akrherz** [comment]
lets try rerendering!

@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
For the sake of visibility the error is:

```
checking build system type... x86_64-apple-darwin13.4.0
Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config/config.sub arm64-apple-darwin20.0.0 failed
```

**Comment by Try2Code** [comment]
on my system the config.log reports
```
configure:3477: checking build system type
configure:3492: result: arm-apple-darwin23.3.0
```

**Comment by Try2Code** [comment]
@ocefpaf @akrherz I tried another tar ball with latest version of config.sub/config.guess leading to a similar error:

```
checking build system type... x86_64-apple-darwin13.4.0
Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config/config.sub arm64-apple-darwin20.0.0 failed
```

So I think the is a miss-behaviour of the building environment.

**Comment by akrherz** [comment]
I am unsure what to suggest :(

**Comment by Try2Code** [comment]
the previous version update (2.4.1) had this test running and it still works (checked with the dummy PR) since then the testing env had these changes:
```
diff --git a/.scripts/run_osx_build.sh b/.scripts/run_osx_build.sh
index 420f051..07dff21 100755
--- a/.scripts/run_osx_build.sh
+++ b/.scripts/run_osx_build.sh
@@ -11,7 +11,7 @@ MINIFORGE_HOME=${MINIFORGE_HOME:-${HOME}/miniforge3}
 ( startgroup "Installing a fresh version of Miniforge" ) 2> /dev/null
 
 MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/latest/download"
-MINIFORGE_FILE="Miniforge3-MacOSX-$(uname -m).sh"
+MINIFORGE_FILE="Mambaforge-MacOSX-$(uname -m).sh"
 curl -L -O "${MINIFORGE_URL}/${MINIFORGE_FILE}"
 rm -rf ${MINIFORGE_HOME}
 bash $MINIFORGE_FILE -b -p ${MINIFORGE_HOME}
```

could be related to recent license changes

**Comment by Try2Code** [comment]
I will close this one and try again. or recent PRs do not show this error :shrug:

**Pull request closed without merging**
