### PR TITLE
update to cdo-1.9.7.1

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Hi @ocefpaf - I removed that kind of optimization for my pull request, but finally I'd llike to have some feetback on this.

Not sure what you mean by optimization. Are you referring to the webservice re-render? That is flaky sometimes but [we can always re-render locally](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally).

> So, do you know if this is portable on the context of a conda package? I am not sure - I successfully build with it on my system, but that's not what I call a _portability test_.

This release is failing with a segfault. I'm trying to build it in our docker image to see if I can debug it.

> I think it would help me to get more info about the remote builting and testing facilities for conda-forge. Can you point me to something like this? thx in advance!

We have some docs on this but they are not comprehensive enough, so feel free to ask any question while you try it: https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally

**Comment by Try2Code** [comment]
with optimization I mean the change ae6eb45, inserting an additional compile-flag ```--tree-vectorize```

the ```make check``` with the locally build binary and on azure (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=42805&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3) worked btw

**Comment by Try2Code** [comment]
I re-rendered it locally without problems
```

Re-rendered with conda-build 3.18.3, conda-smithy 3.4.0, and conda-forge-pinning 2019.06.19
No changes made. This feedstock is up-to-date.

```

**Comment by ocefpaf** [comment]
> with optimization I mean the change [ae6eb45](https://github.com/conda-forge/cdo-feedstock/commit/ae6eb45a45b4363fd7e3e8819390c1fadaf99fa3), inserting an additional compile-flag `--tree-vectorize`

Got it.

> the `make check` with the locally build binary and on azure ([dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=42805&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=42805&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3)) worked btw

Great! Let's merge it!

**Comment by Try2Code** [comment]
I just re-ran the tests with the changes you did !?!

_thx for watching_

**Pull request merged**
