### PR TITLE
Enable aec + magics for CDO (plotting and szip compression for GRIB1)

### PR DESCRIPTION
**Pull request by Try2Code**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks @Try2Code , would need to have the build number bumped and is this of concern?

> 2021-10-05T14:43:04.5096483Z checking netcdf's nc4/szlib support... no

**Comment by Try2Code** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
Oh, you need to create this from your fork and not a branch here as the message states.  Do you need help with that?

**Comment by Try2Code** [comment]
> Thanks @Try2Code , would need to have the build number bumped and is this of concern?
> 
> > 2021-10-05T14:43:04.5096483Z checking netcdf's nc4/szlib support... no

hi!
I wasn't sure if re-render is sufficient for building a new CDO binary in the background. The szip compression I switch on is only for grib1 output. the szlib compression of netcdf can only be done in netcdf, but at the moment CDO does not use it for encoding.

I indeed need better understanding of the conda building process :pray:

**Comment by akrherz** [comment]
> I indeed need better understanding of the conda building process

It appears you already have this repo forked into your personal github account, so that's great.  How are you interacting with github?  You may just need to push your `enable-aec` branch to your remote for your fork.  What does `git remote -v` report within your local `cdo-feedstock` repo?

**Comment by Try2Code** [comment]
I used forks before I became maintainer. But for the change in the PR I actually wanted to use the main repo. I thought it might be easier. idk. 

So in your opinion it's better to stick to personal forks instead?

**Pull request closed without merging**
